sensor_kit_base_link:
# camera
  camera0/camera_link:
    x: 2.6
    y: -0.20
    z: -0.50
    roll: -1.4
    pitch: -0.01
    yaw: -1.6 #낮추면 카메라 시점이 시계방향으로 회전

  camera1/camera_link:
    x: 0.5
    y: 0.0
    z: 0.0
    roll: -1.5
    pitch: 0.0
    yaw: -1.5

# lidar
  # The laser coordinate system is the y-axis toward the front of the car.
  velodyne_top_base_link:
    x: 0.0
    y: 0.0
    z: 0.0
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
  
  velodyne_front_base_link:
    x: 2.4
    y: 0.04
    z: -0.7
    roll: 0.0
    pitch: 0.04
    yaw: 0.06

  gnss_link:
    x: 0.0
    y: 0.0
    z: 0.6
    roll: 0.0
    pitch: 0.0
    yaw: 0.0

  witmotion/imu_link:
    x: -1.0
    y: 0.0
    z: -0.6936
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
